# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(740, 626)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.plotTab = QtWidgets.QWidget()
        self.plotTab.setObjectName("plotTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.plotTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plotTabWidget = QtWidgets.QWidget(self.plotTab)
        self.plotTabWidget.setObjectName("plotTabWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.plotTabWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.filterHLayout = QtWidgets.QHBoxLayout()
        self.filterHLayout.setObjectName("filterHLayout")
        self.cutoffLowLabel = QtWidgets.QLabel(self.plotTabWidget)
        self.cutoffLowLabel.setObjectName("cutoffLowLabel")
        self.filterHLayout.addWidget(self.cutoffLowLabel)
        self.cutoffLowSpinBox = QtWidgets.QDoubleSpinBox(self.plotTabWidget)
        self.cutoffLowSpinBox.setMaximum(99999.99)
        self.cutoffLowSpinBox.setObjectName("cutoffLowSpinBox")
        self.filterHLayout.addWidget(self.cutoffLowSpinBox)
        self.cutoffHighLabel = QtWidgets.QLabel(self.plotTabWidget)
        self.cutoffHighLabel.setObjectName("cutoffHighLabel")
        self.filterHLayout.addWidget(self.cutoffHighLabel)
        self.cutoffHighSpinBox = QtWidgets.QDoubleSpinBox(self.plotTabWidget)
        self.cutoffHighSpinBox.setEnabled(True)
        self.cutoffHighSpinBox.setMaximum(99999.99)
        self.cutoffHighSpinBox.setObjectName("cutoffHighSpinBox")
        self.filterHLayout.addWidget(self.cutoffHighSpinBox)
        self.filterCheckBox = QtWidgets.QCheckBox(self.plotTabWidget)
        self.filterCheckBox.setObjectName("filterCheckBox")
        self.filterHLayout.addWidget(self.filterCheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.filterHLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.filterHLayout)
        self.plotWidget = GraphicsLayoutWidget(self.plotTabWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setMinimumSize(QtCore.QSize(200, 200))
        self.plotWidget.setObjectName("plotWidget")
        self.verticalLayout_2.addWidget(self.plotWidget)
        self.gridLayout_2.addWidget(self.plotTabWidget, 0, 1, 1, 1)
        self.tabWidget.addTab(self.plotTab, "")
        self.keyboardTab = QtWidgets.QWidget()
        self.keyboardTab.setObjectName("keyboardTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.keyboardTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.keyboardTabWidget = QtWidgets.QWidget(self.keyboardTab)
        self.keyboardTabWidget.setObjectName("keyboardTabWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.keyboardTabWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.keyboardHLayout = QtWidgets.QHBoxLayout()
        self.keyboardHLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.keyboardHLayout.setObjectName("keyboardHLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.keyboardHLayout.addItem(spacerItem1)
        self.letterLabel = QtWidgets.QLabel(self.keyboardTabWidget)
        self.letterLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.letterLabel.setObjectName("letterLabel")
        self.keyboardHLayout.addWidget(self.letterLabel)
        self.keyboardLineEdit = QtWidgets.QLineEdit(self.keyboardTabWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyboardLineEdit.sizePolicy().hasHeightForWidth())
        self.keyboardLineEdit.setSizePolicy(sizePolicy)
        self.keyboardLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.keyboardLineEdit.setReadOnly(True)
        self.keyboardLineEdit.setObjectName("keyboardLineEdit")
        self.keyboardHLayout.addWidget(self.keyboardLineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.keyboardHLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.keyboardHLayout)
        self.keyboardWidget = QtWidgets.QWidget(self.keyboardTabWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyboardWidget.sizePolicy().hasHeightForWidth())
        self.keyboardWidget.setSizePolicy(sizePolicy)
        self.keyboardWidget.setMinimumSize(QtCore.QSize(200, 200))
        self.keyboardWidget.setObjectName("keyboardWidget")
        self.verticalLayout.addWidget(self.keyboardWidget)
        self.gridLayout_3.addWidget(self.keyboardTabWidget, 0, 1, 1, 1)
        self.tabWidget.addTab(self.keyboardTab, "")
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cutoffLowLabel.setText(_translate("MainWindow", "Low Cut-Off"))
        self.cutoffHighLabel.setText(_translate("MainWindow", "High Cut-Off"))
        self.filterCheckBox.setText(_translate("MainWindow", "FILTER"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plotTab), _translate("MainWindow", "Plot"))
        self.letterLabel.setText(_translate("MainWindow", "Letter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.keyboardTab), _translate("MainWindow", "Keyboard"))
from pyqtgraph import GraphicsLayoutWidget
